version: '2'
services:

  ikev2-vpn:
    image: alexanderek/ikev2-vpn
    container_name: ikev2-vpn
    restart: always
    ports:
      - 500:500/udp
      - 4500:4500/udp
    cap_add:
     - NET_ADMIN
    environment:
      - HOST=<FQDN or IP>
      - HOSTNAME=ikev2-vpn-aws
